search:
  type: "search"
  target: "GATEWAY"
  executed: false
  shouldRender: true
  config: "search"
  nextRequest: "on_search"
  preRequest: null
  isCollapsed: false
  protocol:
    $ref: ./protocolMapping.yaml#/protocol/search

on_search:
  type: "on_search"
  executed: false
  shouldRender: false
  config: "on_search"
  nextRequest: "select"
  preRequest: "search"
  isCollapsed: false
  protocol:
    $ref: ./protocolMapping.yaml#/protocol/on_search

select:
  type: "select"
  executed: false
  shouldRender: false
  config: "select"
  nextRequest: "on_select"
  preRequest: "on_search"
  isCollapsed: false
  protocol:
    $ref: ./protocolMapping.yaml#/protocol/select

on_select:
  type: "on_select"
  executed: false
  shouldRender: false
  config: "on_select"
  nextRequest: "init"
  preRequest: "select"
  isCollapsed: false
  protocol:
    $ref: ./protocolMapping.yaml#/protocol/on_select

init:
  type: "init"
  executed: false
  shouldRender: false
  config: "init"
  nextRequest: "on_init"
  preRequest: "on_select"
  isCollapsed: false
  protocol:
    $ref: ./protocolMapping.yaml#/protocol/init

on_init:
  type: "on_init"
  executed: false
  shouldRender: false
  config: "on_init"
  nextRequest: "confirm"
  preRequest: "init"
  isCollapsed: false
  protocol:
    $ref: ./protocolMapping.yaml#/protocol/on_init

confirm:
  type: "confirm"
  executed: false
  shouldRender: false
  config: "confirm"
  nextRequest: "on_confirm"
  preRequest: "on_init"
  isCollapsed: false
  protocol:
    $ref: ./protocolMapping.yaml#/protocol/confirm

on_confirm:
  type: "on_confirm"
  executed: false
  shouldRender: false
  config: "on_confirm"
  nextRequest: "track"
  preRequest: "confirm"
  isCollapsed: false
  protocol:
    $ref: ./protocolMapping.yaml#/protocol/on_confirm

# on_update:
#   type: "on_update"
#   executed: false
#   shouldRender: false
#   config: "on_update"
#   nextRequest: "status"
#   preRequest: "on_confirm"
#   isCollapsed: false
#   protocol:
#     $ref: ./protocolMapping.yaml#/protocol/on_update

track:
  type: "track"
  executed: false
  shouldRender: false
  config: "track"
  nextRequest: "on_track"
  preRequest: "on_confirm"
  isCollapsed: false
  protocol:
    $ref: ./protocolMapping.yaml#/protocol/track

on_track:
  type: "on_track"
  executed: false
  shouldRender: false
  config: "on_track"
  nextRequest: status
  preRequest: "track"
  isCollapsed: false
  protocol:
    $ref: ./protocolMapping.yaml#/protocol/on_track

status:
  type: "status"
  executed: false
  shouldRender: false
  config: "status"
  nextRequest: "on_status"
  preRequest: "on_track"
  isCollapsed: false
  protocol:
    $ref: ./protocolMapping.yaml#/protocol/status

on_status:
  type: "on_status"
  executed: false
  shouldRender: false
  config: "on_status"
  nextRequest: null
  preRequest: "status"
  isCollapsed: false
  protocol:
    $ref: ./protocolMapping.yaml#/protocol/on_status
