server:
  port: 80
flows:
  - summary: Metro - Station Code Based Flow
    id: metro-flow-1
    domain: ONDC:TRV11
    shouldDispaly: true
    sessionData:
      version: "2.0.0"
      collectedBy: BAP
      bankAccountNumber: "123456789"
      virtualPaymentAddress: "adasd@okiciic"
      bankCode: "fj3jf9ij3f02"
    input:
      $ref: ./configs/metro-flow-1/input.yaml
    protocol:
      $ref: ./configs/metro-flow-1/protocolMapping.yaml
    calls:
      $ref: ./configs/metro-flow-1/protocolCalls.yaml
    additioalFlows:
      - key: metro cancel flow
        value: metro-cancel-flow-1
  - summary: metro cancel flow
    shouldDispaly: false # check
    id: metro-cancel-flow-1
    domain: ONDC:TRV11
    input:
      $ref: ./configs/metro-cancel-flow-1/input.yaml
    protocol:
      $ref: ./configs/metro-cancel-flow-1/protocolMapping.yaml
    calls:
      $ref: ./configs/metro-cancel-flow-1/protocolCalls.yaml
  - summary: Metro - Station Code Based Flow(without select call)
    id: metro-flow-2
    domain: ONDC:TRV11
    shouldDispaly: true
    sessionData:
      version: "2.0.0"
      collectedBy: BAP
      bankAccountNumber: "123456789"
      virtualPaymentAddress: "adasd@okiciic"
      bankCode: "fj3jf9ij3f02"
    input:
      $ref: ./configs/metro-flow-2/input.yaml
    protocol:
      $ref: ./configs/metro-flow-2/protocolMapping.yaml
    calls:
      $ref: ./configs/metro-flow-2/protocolCalls.yaml
  - summary: On-Demand - Assign driver on on-confirm
    domain: ONDC:TRV10
    shouldDispaly: false
    id: ondemand-flow-1
    sessionData:
      version: "2.0.0"
    input:
      $ref: ./configs/ondemand-flow-1/input.yaml
    protocol:
      $ref: ./configs/ondemand-flow-1/protocolMapping.yaml
    calls:
      $ref: ./configs/ondemand-flow-1/protocolCalls.yaml
  - summary: InterCity(Bus) - Station Code Based Flow
    id: intercity-flow-1
    shouldDispaly: false
    domain: ONDC:TRV12
    sessionData:
      version: "2.0.0"
    input:
      $ref: ./configs/intercity-flow-1/input.yaml
    protocol:
      $ref: ./configs/intercity-flow-1/protocolMapping.yaml
    calls:
      $ref: ./configs/intercity-flow-1/protocolCalls.yaml
